[package]
name = "bigsets"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Kate Légaré"]
license = "MIT"
description = "Collection of math stuff I use often"
repository = "https://github.com/laeva-lady/bigsets"
categories = ["Layout"]
keywords = ["Math"]
exclude = ["*.pdf"]
disciplines = ["mathematics"]
